import logging
from cognivault.agents.critic.agent import CriticAgent
from cognivault.context import AgentContext
import asyncio


logger = logging.getLogger(__name__)


async def run_critic(query: str) -> str:
    """Run the CriticAgent with the given query asynchronously.

    Parameters
    ----------
    query : str
        The input query to evaluate.

    Returns
    -------
    str
        The output generated by the CriticAgent.
    """
    agent = CriticAgent()
    logger.info(f"[{agent.name}] Running agent with query: {query}")
    context = AgentContext(query=query)
    result = await agent.run(context)
    output = result.get_output("Critic") or "[No output]"
    logger.info(f"[{agent.name}] Output: {output}")
    return output


if __name__ == "__main__":  # pragma: no cover
    import sys

    query = input("Enter a query: ").strip()
    output = asyncio.run(run_critic(query))
    print("\n🤔 Critic Output:\n", output)
